image: node:alpine

cache:
    key: "${CI_BUILD_REF_NAME}"
    paths:
        - node_modules/

stages:
    - build
    - test

before_script:
    - npm install

build:
    stage: build
    script:
        - npm run build

test:
    stage: test
    script:
        - npm test
